### ISSUE TITLE
A question about multi-threading and thread safety

### ISSUE THREAD

**Issue by kostya-sh** [spion/hashtable-latencies#4]
This is not a bug report, just a question that I hope you can answer.

Comparing different versions of the applications I can see the following aproaches to avoid data races:
### Go
- Uses a mutex and looks correct
### Node.js
- Doesn't do anything but node.js is single threaded by design
### Reason
- Doesn't do anything but Ocaml is single threaded as far as I know
### Haskell
- Uses MVar for counter however doesn't increment it atomically (https://github.com/spion/hashtable-latencies/blob/master/haskell/app/Main.hs#L32). Could this be a problem?
- Uses  Data.HashTable.IO.BasicHashTable without synchronization. Is it thread safe?
### swift-zewo
- No synchronization. Is it single threaded?

Thank you.

**Comment by spion** [comment]
Swift is single-threaded yes. The language is multi-threaded but the Zewo runtime is based on [libmill](http://libmill.org/) which is single-threaded.

Haskell is "safe-enough" that it doesn't crash.

MVar is a single-value channel which blocks on the next `takeMVar` until there is a new value in the channel (`putMVar`), so the increment is safe. Not sure about BasicHashTable, the mutation should probably be within the `MVar` lock. 

edit: fixed, the hashtable mutation is now done within the lock.

**Comment by kostya-sh** [comment]
Thank you for the reply
