### ISSUE TITLE
Test with 100k requests per second

### ISSUE THREAD

**Issue by kostya-sh** [spion/hashtable-latencies#8]
10k requests per second is fairly low as the application is hardly doing anything.

It would be intresting to see the results with 100k requests per second.

Even better would be to see the breaking point for each application.

**Comment by spion** [comment]
This is actually not that interesting to me. There are many benchmarks that measure throughput. I want this one to isolate only GC-caused latency and pauses. Infact I considered lowering the RPS even more but the test would take too long.

If we force more requests than the implementation can normally handle, we are no longer measuring GC latencies, but a weird mixture of GC latency and maximum-throughput-caused latency 😄 

Sorry to shoot down the proposal so quickly, but I want to keep the scope small. Obviously, feel free to fork and experiment 👍
